services:
  hive-app:
    build:
      context: .
      dockerfile: ./src/app/Hive.App/Dockerfile
    image: localhost/hive-app:latest
    container_name: hive-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - hive-network
  hive-idm:
    build:
      context: .
      dockerfile: ./src/idm/Hive.Idm.Api/Dockerfile
    image: localhost/hive-idm:latest
    container_name: hive-idm
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
    restart: unless-stopped
    networks:
      - hive-network
  hive-watcher:
    build:
      context: .
      dockerfile: ./src/app/Watcher.Console.App/Dockerfile
    image: localhost/hive-watcher:latest
    container_name: hive-watcher
    command: [ "--watch", "/app/shared" ]
    volumes:
      - "/home/user/shared/Plex/Shared Movies:/app/shared"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - hive-network
  project-hive-web:
    build:
      context: .
      dockerfile: ./src/web/Dockerfile
    image: localhost/project-hive-web:latest
    container_name: project-hive-web
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "app=project-hive-web"
      - "maintainer=project-hive"
    networks:
      - hive-network
networks:
  hive-network:
    driver: bridge
