services:
  hive-app:
    build:
      context: .
      dockerfile: ./src/app/Hive.App/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: localhost/hive-app:latest
    container_name: hive-app
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - hive-network
  hive-idm:
    build:
      context: .
      dockerfile: ./src/idm/Hive.Idm.Api/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: localhost/hive-idm:latest
    container_name: hive-idm
    ports:
      - "0.0.0.0:8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082
      - RabbitMQ__HostName=rabbitmq_broker
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin
    restart: unless-stopped
    networks:
      - hive-network
  hive-watcher:
    build:
      context: .
      dockerfile: ./src/app/Watcher.Console.App/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: localhost/hive-watcher:latest
    container_name: hive-watcher
    volumes:
      - "/home/user/shared:/mnt/host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq_broker
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin
    restart: unless-stopped
    depends_on:
      - hive-app
      - hive-idm
    networks:
      - hive-network
    healthcheck:
      test: [ "CMD", "test", "-d", "/mnt/host" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  hive-meta-scraper:
    build:
      context: .
      dockerfile: ./src/app/MetaScraper.App/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: localhost/hive-meta-scraper:latest
    container_name: hive-meta-scraper
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq_broker
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin
    restart: unless-stopped
    depends_on:
      - hive-app
      - hive-idm
    networks:
      - hive-network
    healthcheck:
      test: [ "CMD", "test", "-d", "/mnt/host" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  project-hive-web:
    build:
      context: .
      dockerfile: ./src/web/Dockerfile
    image: localhost/project-hive-web:latest
    container_name: project-hive-web
    ports:
      - "0.0.0.0:8000:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - AUTH_BASE_URL=http://192.168.1.55:8082
      - MOVIES_BASE_URL=http://192.168.1.55:8080
      - JELLYFIN_BASE_URL=http://192.168.1.112:8096
      - JELLYFIN_ACCESS_TOKEN="00f46625e4f6440dabcb040fef21df79"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "app=project-hive-web"
      - "maintainer=project-hive"
    depends_on:
      - hive-app
      - hive-idm
    networks:
      - hive-network
  
networks:
  hive-network:
    driver: bridge
